

# library(tidyverse)
# ## Some stats packages:
# library(stats)
# library(car)
# ## Packages for making tables (AIC tables, frequency tables):
# library(gtsummary)
# library(AICcmodavg)
# library(gt)
# # ## Packages for editing plots:
# library(effects)
# library(ggpubr)
# library(cowplot)
# library(formatR)
# ## Diagnostics:
# library(corrplot)
# library(detectseparation)

# now = format(Sys.time(), "%m%d_%H%M_")
#

### INTERNAL FUNCTIONS   ##############################################################
#
# ONLY WORKS FOR THESE MODELS BECAUSE OF HOW I CONSTRUCTED THEM (using paste)
# The regex does not work for regular lm calls
#
# - modnames function:
#  - extract the model call statements using deparse
#  - format the extracted strings
#       e.g. interactions: make 'var1*var2' into 'var1+var2+var1:var2'
#  - replace the variable names with the formatting my advisor asked for


#' Reformat model formulas to be included in tables.
#'
#' @param mods The model list generated for use with run_mods
#' @param null Include the name for the null model (second model in list)? default: TRUE
#' @param debug Include debugging print statements? (default: FALSE)
#'
#' @returns A list of the reformatted equations in the order they were specified. It will always name the second model in the list "NULL"
#' @export
#'
modnames <- function(
    # mods, null=TRUE, debug=FALSE
    mods, null=TRUE, debug=FALSE
    ){
  dp <- function(x) deparse(x, width.cutoff=150)
  if(is.list(mods)){
    modEQ <- paste(sapply(
      mods,
      function(x) stringr::str_extract(dp(x$formula), "(?<=~\\s).*")
      # function(x) stringr::str_extract(x$formula, "(?<=~\\s)(.*)  ")
    ), sep = ",")
  } else {
    modEQ <- stringr::str_extract(mods, "(?<=~\\s).*")
  }
  modEQ <- stringr::str_replace_all(modEQ, c(
    "species" = "SPECIES",
    "obs_int" = "FINAL_INTERVAL",
    "cam_fate" = "TRUE_FATE",
    "nest_age" = "NEST_AGE",
    "fdate" = "END_DATE",
    "1"     = "NULL"))
  # cat("mod equations before substitution:", modEQ)
  if(debug) message(paste("\nmod equations before substitution: ", modEQ))
  # print(con=stdout(), "mod equations before substitution:", modEQ)
  m <- stringr::str_match(modEQ, "(\\w+)\\s\\*\\s(\\w+)" )
  # don't want to replace wheree this is no match (just replaces with NA)
  # modEQ <- stringr::str_replace(modEQ[!is.na(m)], coll(m[,1]), coll((paste0(m[,2]," + ",m[,3]," + ",m[,2],":",m[,3]))))
  modEQ <- ifelse(!is.na(m[,1]),
                  str_replace(modEQ, coll(m[,1]), paste0(m[,2]," + ",m[,3]," + ", m[,2],":",m[,3])),
                  modEQ
  )
  # if(debug) message(paste("\nand again after str_match", m))
  if(debug) message(paste("\nand again after str_match/str_replace:", modEQ))

  return(modEQ)
}

dp <- function(x) deparse(x, width.cutoff=150)



##### EXTERNAL FUNCTIONS: ###########################################################

############## MOD_DIFF #################################################

#' Compare coefficients of any 2 different models
#'
#' @param mOne  first model being compared
#' @param mAlt  second model being compared
#' @param modtype  I don't think this does anything
mod_diff <- function(mOne, mAlt, modtype){ # argument order matters - names should help

  difVList <- which(!(names(stats::coef(mOne))) %in% names(stats::coef(mAlt)))

  comp <- stats::anova(mOne, mAlt, test="LRT")
  cat("\nCompare to full model:\n\n")
  print(comp)

  cat("\n\nPercent difference in model coefficients (vs full model):\n\n")
  cat(names(stats::coef(mOne))[-difVList], "\n")
  cat((abs(stats::coef(mAlt)-stats::coef(mOne)[-difVList]) / stats::coef(mOne)[-difVList])) #
  cat("\n---------------------------------------------------------------")
}

#' Generate odds ratios for a set of models
#'
#' @param mods list of model summaries (generated by the run_models function)
#'
#' @returns list of odds ratios
#' @export
#'
odd_rat <- function(mods){
  oddrats <- paste(sapply(mods, function(x) exp(x$coefficients)), sep=' ')
  names(oddrats) <- paste0("OR_mod",seq_along(mods))
  return(oddrats)
}

############## AIC_MOD #################################################

#' Create an AIC table to rank a set of models
#'
#'  1. Create the model equations using the modnames function
#'  2. Create an AIC table; use an alternate function if the default throws an error
#'  3. Reformat the AIC table using gt to make it look nice
#'
#' @param mods list of model summaries (generated by the run_models function)
#'
#' @importFrom magrittr %>%
#' @importFrom rlang .data
#' @returns the AIC table itself
#' @export
aic_mod <- function(mods){
 modEQ = modnames(mods)
  # modEQ = sapply(mods, function(x) stringr::str_extract(dp(x$formula)))
  nestAIC <- tryCatch(
    {
      AICcmodavg::aictab(cand.set = mods, modnames = modEQ, sort = T) %>%
        dplyr::mutate(df = .data$K-1) %>%
        cat("k=", .data$K, "df=", .data$df) %>%
        cat("; mod names=\n", paste(.data$Modnames, sep="\n")) %>%
        dplyr::select(.data$Modnames, ,.data$AICc, .data$Delta_AICc, .data$df, .data$AICcWt, .data$LL)
        # rename()
    },
    error=function(e){

        cat("using bbmle; mod names=\n", paste(modEQ, sep="\n"))
        bbmle::AICctab(mods, weights=TRUE, logLik=TRUE, base=TRUE, nobs=121, mnames=modEQ) %>%
          as.data.frame() %>%
          dplyr::select(.data$df, .data$AICc, .data$dAICc, .data$weight, .data$logLik, .data$dLogLik)

        # error when trying to get the logLik:
        # Error in h(simpleError(msg, call)) :
        #error in evaluating the argument 'object' in selecting a method for function '
        #AICc': no applicable method for 'logLik' applied to an object of class "list"
    }
  )
   AICtab <- nestAIC %>%
    # select(Modnames, K, Delta_AICc, AICc, AICcWt, LL) %>% # COLUMN SELECTION
    # select(dAICc, df, dLogLik, weight) %>% # COLUMN SELECTION
    # select()
    # as.data.frame() %>%
    dplyr::mutate(
      dplyr::across(
        dplyr::where(is.numeric), ~round(.x, digits=2))) %>%
    gt::gt(rownames_to_stub = TRUE) %>%
    # fmt_number(columns=everything(), rows=everything(), decimals=2) ## ROUNDING
    # tab_header(title="AIC scores") %>%
    #gt::tab_header(title=paste("AIC scores -", question)) %>%
    gt::tab_header(title=paste("AIC scores")) %>%
    # tab_style(
      # style = cell_text
      # style = cell_text(size="small"),
      #         locations= cells_body())
    # )
    gt::tab_options(
      # table.font.weight = "bold",
      # was going to try setting whole table to bold and then body cells to normal
      column_labels.font.weight = "bold"
    ) %>%
    # cols_label(
    #
    # )%>%
     # the footnotes are messing up save_tab for some reason. gives a list of length 653.
    # gt::tab_footnote(paste("Modeled using", dp(mods[[1]]$method), "method"))
  return(AICtab)
}

############## BIC_MOD #################################################

#' Generate a BIC table for the models
#'
#' @param mods list of model summaries (generated by run_mods)
#'
#' @return table of models ranked by BIC score
#' @export
#'
bic_mod <- function(mods){

  modEQ <- paste(sapply(mods,
                        function(x) stringr::str_extract(dp(x$call), "(?<=~\\s).+(?=,\\sf)")
                        ), sep = " ")

  nestBIC <- AICcmodavg::bictab(cand.set = mods, modnames = modEQ, sort = T) # include VIF?

  BICtab <- gt::gt(nestBIC) %>%
    gt::tab_header(title="BIC scores") %>%
    gt::tab_style(style =
                gt::cell_text(size="small"),
              locations = gt::cells_body())
  return(BICtab)
}

############## TABREGR ################################################

#' Create & save regression table
#'
#' @description
#' Create and save a regression table for the top model(s)
#' You just input which model (number) and the function will create the table
#' Still needs work to get the labels right
#'
#' @param modNum tells function which model to create the regression table for
#' @param mods list of model summaries, generated by run_models
#' @param resp the response variable
#' @param suffix add suffix (good for multiple tables made within same timestamp) default = None
#' @param vars  vector of predictors; default=c('species', 'nest_age', 'obs_int', 'cam_fate', 'fdate')
#' @param newNames new names to give the predictors; order should match. default = c('SPECIES', 'NEST_AGE', 'FINAL_INTERVAL', 'TRUE_FATE', 'END_DATE')
#' @param debug  default = FALSE
#'
#' @returns regression table with exponentiated log odds ratios
#' @export
#'
tabRegr <- function(modNum, mods, resp,
                    vars=c('species', 'nest_age', 'obs_int', 'cam_fate', 'fdate'),
                    newNames=c('SPECIES', 'NEST_AGE', 'FINAL_INTERVAL', 'TRUE_FATE', 'END_DATE'),
                    suffix="",
                    debug=F){
  # browser()
  now = format(Sys.time(), "%m%d_%H%M%S") # seconds bc tables all generated in < 1 min
  nm       <- function(x) substitute(x)
  if (resp=="is_u"){
    r = "MARKED_UNKNOWN"
  } else if(resp=="HF_mis" | resp=="misclass"){
    r = "MISCLASSIFIED"
  }
  if(debug) cat("response is", r, "\n\n")
  modEQ <- paste(sapply(
    mods,
    function(x) stringr::str_extract(dp(x$call), "(?<=~\\s)(.*)(?=\")")
    ), sep = " ")
  modVar <- stringr::word(modEQ)# extracts words
  if(debug) cat("extracted mod var:", modVar, "\n\n")
  # vars <- c('species', 'nest_age', 'obs_int', 'cam_fate', 'fdate')
  # newName <- c('SPECIES', 'NEST_AGE', 'FINAL_INTERVAL', 'TRUE_FATE', 'END_DATE')
  varNames <- ifelse(vars %in% modVar, paste(vars,"~'", newNames,"'",sep=""), NA)
  varNames <- varNames[!is.na(varNames)]
  vn <- as.list(varNames) #maybe all of this is not necessary?
  # vnames <- list(
  #   species  = "SPECIES",
  #   nest_age = "NEST_AGE",
  #   cam_fate = "TRUE_FATE",
  #   obs_int  = "FINAL_INTERVAL",
  #   fdate    = "END_DATE"
  # )
  # vnames <- list(unlist(newNames))
  vnames <- as.list(newNames)
  if(debug) print(vnames)
  names(vnames) <- vars
  if(debug) print(vnames)
  tabOR <- gtsummary::tbl_regression(mods[[modNum]],
                          label = vnames,
                          # label= list(
                          #   # resp~paste(r), # can't label response var
                          #             species~"SPECIES",
                          #             nest_age~"NEST_AGE",
                          #             obs_int~"FINAL_INTERVAL",
                          #             cam_fate~"TRUE_FATE",
                          #             fdate~"END_DATE"),
                          exponentiate=T)
    # as_gt() %>%
    # tab_header(title=paste(question))
  # so the tbl_regression function is already returning an image?
  # it says "publication-ready"
  # I guess it just needs to be as_gt
  headr <- paste("Regression Summary for Model:",
                 modnames(list(x = mods[[modNum]]), null=FALSE),
                 sep="\n")


  now = format(Sys.time(), "%m%d_%H%M_")
  filename3  <- sprintf("reg_%s_%s.rtf", now, suffix)
  filename4  <- sprintf("reg_%s_%s.png", now, suffix)
  # tabOR %>% gt() %>% gtsave(filename=filename3, path="analysis/", vwidth=1200, vheight=800)
  tabOR %>%
    gtsummary::as_gt() %>%
    # gt::tab_header(title=paste(question)) %>%
    gt::tab_header(title=headr) %>%
    gt::gtsave(filename=filename3, path="analysis/", vwidth=1200, vheight=800)


  tabOR %>%
    gtsummary::as_gt() %>%
    # gt::tab_header(title=paste(question)) %>%
    gt::tab_header(title=headr) %>%
    gt::gtsave(filename=filename4, path="analysis/", vwidth=1200, vheight=800)

  # return(tabOR)
  return( filename4)
}




############## SAVE_TAB ################################################
#
#' Save any table
#' - Save tables to file and enable inclusion in the knitted output by returning the file name.
#' - Save as png and rtf

#'
#' @param tab the table to be saved; should be in gtable format
#' @param dpi choose DPI of the image file. default is 1800/6. right now this isn't used.
#' @param suffix specify filename suffix (can include which data are used, settings, etc)
#' @param rtf should the function also generate an rtf file in addition to the png? default: FALSE
#' @param dir Directory where file will be saved
#'
#' @returns the name of the png file so it can be used with knitr in an Rmd document
#' @export
#'
save_tab <- function(tab, dpi=(1800/6), dir, suffix="", rtf=FALSE){

  now = format(Sys.time(), "_%m%d_%H%M%S") # seconds bc tables all generated in < 1 min
  nm       <- function(x) substitute(x)
  # dpi      <- (1800/6)                          # img width (px) / desired img width (in)
  if(rtf){
    file_name <- paste0(nm(tab), now, suffix, ".rtf")
    gt::gtsave(tab, file_name, path=paste0(dir,"analysis/"))
  }

  file_name1 <- paste0(nm(tab), now, suffix, ".png")
  gt::gtsave(tab, file_name1, path=paste0(dir,"analysis/"))

  # file_name2 <- paste0(nm(tab), now, "_rounded.png")
  # tab2 <- tab %>% fmt_number(decimals=2)
  # gtsave(tab2, file_name2, path-"analysis/")
  return(file_name1)
}












