---
title: "imputation analysis"
author: "Sarah Bolinger"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
  pdf_document: default
params:
  nrun: 19 
  deb: TRUE
  xdeb: TRUE
  ipl: TRUE
  hdir: "C:/Users/sarah/Dropbox/Models/fate_glm/"
  lin: FALSE
  m: 5
  test: TRUE
---

DESIGNED FOR SMALL NUMBERS OF SIMULATIONS ON WINDOWS!

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(knitr.duplicate.label = "allow")
library(brglm2) # penalized logistic regression
library(CALIBERrfimpute) # could access using ::
library(gt)
library(gtsummary)
library(tidyverse)
source("mice_functions.R")
# source("imp_sim_functions.R")
source("imp_sim_functions-DEBUG.R")
source("missing_data.R")
source("other_imp.R")
```


### Remove values from the data to test the efficiency of the imputation with different methods

#### Specify vars, imputation methods, etc:

```{r, warning=FALSE}
# source("GLM_ampute.R")
suffix <- sprintf("%sruns", params$nrun)
cat(">> home directory:", params$hdir, "\t> & number of runs:", params$nrun, "\t> & output suffix:", suffix)

modList <- readLines("modList.txt")
mods4sim <- modList[c(1,8,16) ]
names(mods4sim) <- c("m1", "m8", "m16")

dat4sim <- read.csv("dat_complete.csv", stringsAsFactors = TRUE)
dat4sim$cam_fate <- relevel(dat4sim$cam_fate, ref="H")
dat4sim$species <- relevel(dat4sim$species, ref="LETE")
levels(dat4sim$HF_mis) <- c(0,1)
levels(dat4sim$is_u)   <- c(0,1)
```


```{r, warning=FALSE}
# made the responses into "yes/no" so I could import them automatically as factors
prVars <- c("species", "cam_fate", "obs_int", "nest_age", "fdate")
resp_list <- c("is_u", "HF_mis")

var_list <-  c("nest_age", "cam_fateD", "cam_fateA", "cam_fateF", "cam_fateHu", "cam_fateS", "speciesCONI", "speciesCONI:nest_age", "speciesCONI:obs_int", "obs_int", "fdate") # all vars

bias_names <- c("value","bias", "pctBias", "covRate", "avgWidth", "RMSE", "SD")

met_list <- c("default","pmm", "rf", "cart", "caliber","passive", "stratify","cc")# don't need full here?

if (params$test){ 
  # met_list <- c("default", "passive", "stratify", "cc", "rf") # 1 representative from each if-statement
  # met_list <- c("passive", "stratify", "rf")  # more reduced list
  # met_list <- c("passive", "stratify")  # more reduced list
  # bias_names <- c("pctBias", "covRate", "RMSE")
  # bias_names <- c("pctBias", "covRate")
  # params$xdeb <- TRUE# doesn't work - "cannot change value of locked binding for 'params'"
  # params$ipl <- FALSE
  # params$nrun <- 2# doesn't work - "cannot change value of locked binding for 'params'"
}

formulas <- readRDS("form_lists.rds")
metLists <- readRDS("met_lists.rds")
names(metLists)[3]

cat("\n\n>> number of imputations:", params$m, class(params$m))
cat("\t>> & methods to test:", met_list)
cat("\n\n>> bias to be calculated:", bias_names, "\n")
cat("\n\n>>>> date & time:", format(Sys.time(), "%d-%b %H:%M\n"))

```

#### Run the simulation & calculate the bias:

```{r, warning=FALSE}
# # Create the simulated data with NAs (using the complete-case df):
# # sim_dat <- mkSimDat(nd = ndGLM_scl_cc,col_sel=col_sel, method = "amp", wt = TRUE, debug = TRUE, convFact = TRUE)
# sim_dat <- mkSimDat(nd = dat4sim, vars=var_list, method = "amp", wt = TRUE, debug = params$deb, convFact = TRUE)
# # sim_dat <- mkSimDat(nd = ndGLM_scl_cc, method = "amp", wt = TRUE, debug = debug, convFact = TRUE)
# missing_tab("sim_dat",prVars,)
```

```{r sim, fig.dim=c(12,5)}
if(FALSE){
  r <- "is_u"
  
}
for(r in resp_list){
  # col_sel <- c(prVars,r) # columns to select, as strings
  col_list<- c(prVars,r) # columns to select, as strings
  form_list <- formulas[[r]]
  # col_sel
  # if(params$deb){
  cat("\n\n********************************************************************************************")
  # cat("\n>> response:", r,"\n\t& columns for imputation:", col_sel)
  cat("\n>> response:", r,"\n\t& columns for imputation:", col_list)
  cat("\n********************************************************************************************\n\n")
  # imp_sim <- runSim(fullDat=dat4sim,col_sel = col_list,mets = met_list, resp = r, vars = var_list, mods = mods4sim,par=params) # don't want to set seed
  imp_sim <- runSim(fullDat=dat4sim,col_sel = col_list,mLists = metLists,forms=form_list, resp = r, vars = var_list, mods = mods4sim,par=params) # don't want to set seed
  
  if(params$deb){
    cat("\n\n********************************************************************************************\n")
    cat(">>>>> CALCULATE BIAS VALUES: \n")
    cat("********************************************************************************************\n")
  }
  
  bias_out <- parAvg(fullDat = dat4sim, impDat = imp_sim,hdir = params$hdir,resp = r, vars = var_list, mods=mods4sim, mets = met_list, biasVals = bias_names, debug = params$deb, xdebug=params$xdeb)
  if(params$deb) print(bias_out)
  
}
```


```{r eval=FALSE, warning=FALSE, include=FALSE}
for(z in seq_along(mods4sim)){
  # , cat("\n>>model:", names(model), model)
  cat("\n********************************************************************************************\n")
  cat("\n********************************************************************************************\n")
  cat("\n/////////////////////////////////////////////////////////////////////////////////////////////\n")
  cat("\n********************************************************************************************\n")
  cat("\n>>model:", names(mods4sim)[z], " | ", mods4sim[z])
  cat("\n********************************************************************************************\n")
  cat("\n/////////////////////////////////////////////////////////////////////////////////////////////\n")
  cat("\n********************************************************************************************\n")
  cat("\n********************************************************************************************\n")
  for(r in resp_list){
    col_sel <- c(prVars,r) # columns to select, as strings
    cat("\n\n********************************************************************************************\n")
    cat("\n********************************************************************************************\n")
    cat("\n>> response:", r,"\n\t& columns for imputation:", col_sel)
    cat("\n********************************************************************************************\n")
    cat("\n********************************************************************************************\n")
    # imp_sim <- runSim(datNA = sim_dat$amp,col_sel = col_sel,mets = met_list, resp = resp, vars = var_list, mod = mod4sim, nruns=nrun, debug = FALSE) # don't want to set seed
    # imp_sim <- runSim(dat=ndGLM_scl_cc, datNA = sim_dat$amp,col_sel = col_sel,mets = met_list, resp = r, vars = var_list, mod = mod4sim, nruns=nrun, debug = debug) # don't want to set seed
    # imp_sim <- runSim(datNA = sim_dat$amp,col_sel = col_sel,mets = met_list, resp = r, vars = var_list, mod = mod4sim, nruns=nrun, debug = debug) # don't want to set seed
    imp_sim <- runSim(datNA = sim_dat$amp,col_sel = col_sel,mets = met_list, resp = r, vars = var_list, mod = mods4sim[z], nruns=nrun, debug = debug) # don't want to set seed
    # bias_out <- parAvg(fullDat = ndGLM_scl_cc, impDat = imp_sim,resp = r, vars = var_list, mod = mod4sim,mets = met_list, biasVals = bias_names, debug = debug)
    # bias_out <- parAvg(fullDat = ndGLM_scl_cc, impDat = imp_sim,resp = r, vars = var_list, mod = mods4sim[z], mets = met_list, biasVals = bias_names, debug = debug)
    bias_out <- parAvg(fullDat = dat4sim, impDat = imp_sim,resp = r, vars = var_list, mod = mods4sim[z], mets = met_list, biasVals = bias_names, debug = debug)
    # biasfile <- paste0(params$home_dir, sprintf("out/bias_vals_%s_%s.rds", r, names(mods4sim)[z]))
    biasfile <- paste0(hdir, sprintf("out/bias_vals_%s_%s_%s.rds", r, names(mods4sim)[z], params$suffix))
    # saveRDS(bias_out, sprintf("out/bias_vals_%s_%s.rds",r, names(mods4sim)[z]))
    saveRDS(bias_out, biasfile)
    biasfile1 <- paste0(hdir, sprintf("out/bias_vals_%s_%s_%s.csv", r, names(mods4sim)[z], params$suffix))
    # biasfile1
    # write.csv(bias_out, file = sprintf("out/bias_vals_%s_%s.csv", r, names(mods4sim)[z]))# write to csv in case script aborts 
    # write.csv(bias_out, file = biasfile1, row.names = FALSE)# write to csv in case script aborts 
    ## NOTE - NEED ROW NAMES - that's where the param names are stored |> 
    write.csv(bias_out, file = biasfile1)# write to csv in case script aborts 
    cat("\n\n********************************************************************************************\n")
    cat(">>>>> BIAS VALUES: \n")
    cat("********************************************************************************************\n")
    print(bias_out) # print the output to console
    # cat("\n******************************************************************************************\n")
  }
}
# imp_sim <- runSim(datNA = sim_dat$amp,col_sel = col_sel,mets = met_list, resp = resp, vars = var_list, mod = mod,seed=61389, nruns=nrun)
# saveRDS(imp_sim, "imp_sim_20oct.rds")
```

#### Calculate the bias:

```{r eval=FALSE, warning=FALSE, include=FALSE}
bias_out <- parAvg(fullDat = ndGLM_scl_cc, impDat = imp_sim,resp = resp,vars = var_list, mod = mod4sim,mets = met_list, biasVals = bias_names)
write.csv(bias_out, file = "bias_vals.csv")# write to csv in case script aborts 
bias_out # print the output to console
```


```{r eval=FALSE, warning=FALSE, include=FALSE}
fitReal <- glm(as.formula(paste0(resp, mod4sim)), data=ndGLM_scl_cc, family=fam, method=regMet, control=brglmControl(maxit=iter) )
# 
# trueVals <- coef(fitReal)[var_list]
# test_avg(sim_dat, fitReal)
test_avg(imp_sim, fitReal)
```

#### Test different methods for dealing with the interactions:

```{r}

```
